/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import helper.VersionEImageIcon;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author MUTNPROD003
 */
public class LoginRuta extends javax.swing.JFrame {

  private boolean isFile;

  /**
   * Creates new form LoginRuta
   */
  public LoginRuta() {
    initComponents();
    VersionEImageIcon versionEImageIcon = new VersionEImageIcon(this)
   ;
    versionEImageIcon.newColor();
    jPanel1.setBackground( versionEImageIcon.newColor());
    jButton1.setEnabled(true);
    setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    checkIDC = new javax.swing.JCheckBox();
    informacion = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Arbol de Imagenes");
    setBackground(new java.awt.Color(255, 255, 255));
    setForeground(new java.awt.Color(255, 255, 255));

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Ingrese Ruta del Volumen");

    jTextField1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jTextField1.setText("C:\\Angeles\\201111L06V02\\GND#201111L06V02#GEN_00000002#SL000187");

    jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jButton1.setText("Mostrar");
    jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 255, 204)));
    jButton1.setEnabled(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    checkIDC.setText("Es un IDC");
    checkIDC.setOpaque(false);

    informacion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    informacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Proceso"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.lightGray));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
          .addComponent(informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(checkIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkIDC)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      isVolumenorIDC();
    }//GEN-LAST:event_jButton1ActionPerformed
  private void volumen(String path) {
    File file = new File(path);
    FileFilter fileFilter = new FileFilter() {
      @Override
      public boolean accept(File file) {
        return file.isDirectory();
      }
    };
    if (file.exists())
      {
      isFile = true;
//      principal = new VentanaPrincipal(isFile, this, ruta, informacion);
      new NuevoFrame(isFile, this, path, informacion);
      jButton1.setEnabled(false);
      } else
      {
      setMensajeFileNotFound();
      }
  }

  private void idc(String pathIdc) {
    File folder = new File(pathIdc);
    FileFilter filefilter = new FileFilter() {
      @Override
      public boolean accept(File file) {
        return file.isFile();
      }
    };
    if (folder.exists())
      {
      NuevoFrame nuevoFrame = new NuevoFrame(isFile, this, pathIdc, informacion);
      jButton1.setEnabled(false);
      isFile = false;
      } else
      {
      setMensajeFileNotFound();
      }
  }

  private void isVolumenorIDC() {
    if (isRutaVolumen() && !checkIDC.isSelected())
      {
      volumen(getRuta());
      } else if (!isRutaVolumen() && checkIDC.isSelected())
      {
      idc(getRuta());
      } else
      {
      JOptionPane.showMessageDialog(null, "Modifique la ruta o habilite/deshabilite "
              + "el checkbox\n para para que coincida con la opción seleccionada",
              "Incongruencias entre la ruta y la opción", JOptionPane.ERROR_MESSAGE);
      jTextField1.setText("");
      }
  }

  private boolean isRutaVolumen() {
    return !jTextField1.getText().toString().contains("#");
  }

  private String getRuta() {
    //me aseguro de que no haya espacios en blanco
    return jTextField1.getText().trim();
  }
  /**
   * @param args the command line arguments
   */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginRuta().setVisible(true);
//            }
//        });
//    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkIDC;
  private javax.swing.JLabel informacion;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

  private void setMensajeFileNotFound() {
    String mensaje = "La ruta especificada no es válida.\nVerifique la escritura de la misma";
    JOptionPane.showMessageDialog(null, mensaje, "Error en la escritura de la ruta", JOptionPane.ERROR_MESSAGE);
    jTextField1.setText("");
  }


}
